/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nomer1;

import javax.swing.JOptionPane;
import static nomer1.Nomer1.list_user;

/**
 *
 * @author Lenovo
 */
public class FormLogin extends javax.swing.JFrame {

      /**
       * Creates new form FormLogin
       */
      public FormLogin() {
            initComponents();
            reset_field();
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            txtName = new javax.swing.JTextField();
            txtPass = new javax.swing.JTextField();
            login = new javax.swing.JButton();
            register = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jLabel1.setText("Login");

            jLabel2.setText("Username :");
            jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

            jLabel3.setText("Password :");
            jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

            login.setText("Login");
            login.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        loginActionPerformed(evt);
                  }
            });

            register.setText("Register");
            register.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        registerActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                          .addComponent(jLabel2)
                                          .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                          .addComponent(txtName)
                                          .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(143, 143, 143)
                                    .addComponent(jLabel1))
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addComponent(login)
                                    .addGap(47, 47, 47)
                                    .addComponent(register)))
                        .addContainerGap(45, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel2)
                              .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel3)
                              .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(login)
                              .addComponent(register))
                        .addContainerGap(24, Short.MAX_VALUE))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
            String nama = txtName.getText();
            String pass = txtPass.getText();
            
            int idx = cari_nama(nama);
            if (idx != -1) {
                  User us = list_user.get(idx);
                  if (us.getPassword().equals(pass)) {
                        FormUser f = new FormUser(us);
                        f.setVisible(true);
                        this.dispose();
                  } else {
                        JOptionPane.showMessageDialog(null, "Password salah !");
                  }
            } else {
                  JOptionPane.showMessageDialog(null, "Username tidak ditemukan");
            }
            reset_field();
      }//GEN-LAST:event_loginActionPerformed

      private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
            String nama = txtName.getText();
            String pass = txtPass.getText();
            
            if (!nama.equals("") && !pass.equals("")) {
                  if (cari_nama(nama) == -1) {
                        list_user.add(new User (nama, pass, 0));
                        JOptionPane.showMessageDialog(null, "Sukses register !");
                  } else {
                        JOptionPane.showMessageDialog(null, "Username sudah terdaftar !");
                  }
            } else {
                  JOptionPane.showMessageDialog(null, "Semua field harus diisi !");
            }
            reset_field();
      }//GEN-LAST:event_registerActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new FormLogin().setVisible(true);
                  }
            });
      }
      
      public int cari_nama(String nama) {
            int idx = -1;
            for (int i = 0; i < list_user.size(); i++) {
                  User us = list_user.get(i);
                  if (us.getNama().equals(nama)) {
                        idx = i;
                  }
            }
            return idx;
      }
      
      public void reset_field() {
            txtName.setText("");
            txtPass.setText("");
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JButton login;
      private javax.swing.JButton register;
      private javax.swing.JTextField txtName;
      private javax.swing.JTextField txtPass;
      // End of variables declaration//GEN-END:variables
}
