/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nomer1;

import javax.swing.DefaultListModel;

/**
 *
 * @author Lenovo
 */
public class FormBrowse extends javax.swing.JFrame {

      User us;
      String mode = "off";
      
      public FormBrowse() {
            initComponents();
      }
      
      public FormBrowse(User u) {
            us = u;
            initComponents();
            print();
            judul.setText("-");
            muter.setText("-");
            button();
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            listLagu = new javax.swing.JList<>();
            back = new javax.swing.JButton();
            jLabel2 = new javax.swing.JLabel();
            a = new javax.swing.JLabel();
            b = new javax.swing.JLabel();
            judul = new javax.swing.JLabel();
            muter = new javax.swing.JLabel();
            b_denger = new javax.swing.JButton();
            clear = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setText("Browse Lagu");

            listLagu.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        listLaguMouseClicked(evt);
                  }
            });
            jScrollPane1.setViewportView(listLagu);

            back.setText("Back to Form User");
            back.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        backActionPerformed(evt);
                  }
            });

            jLabel2.setText("Informasi Lagu");

            a.setText("Judul :");

            b.setText("Jumlah Pemutaran :");
            b.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

            judul.setText("-");

            muter.setText("-");
            muter.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

            b_denger.setText("Dengar Lagu");
            b_denger.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        b_dengerActionPerformed(evt);
                  }
            });

            clear.setText("Clear");
            clear.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        clearActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(back))
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                      .addComponent(jLabel2)
                                                      .addComponent(a)
                                                      .addComponent(b))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(judul)
                                                      .addComponent(muter)))
                                          .addGroup(layout.createSequentialGroup()
                                                .addComponent(b_denger)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(clear)))))
                        .addContainerGap())
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jLabel1)
                              .addComponent(back))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1)
                                    .addContainerGap())
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(a)
                                          .addComponent(judul))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(b)
                                          .addComponent(muter))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(b_denger)
                                          .addComponent(clear))
                                    .addContainerGap(131, Short.MAX_VALUE))))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void b_dengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_dengerActionPerformed
            int idx = listLagu.getSelectedIndex();
            us.tambah_puter(idx);
            judul.setText("-");
            muter.setText("-");
            print();
      }//GEN-LAST:event_b_dengerActionPerformed

      private void listLaguMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listLaguMouseClicked
            int idx = listLagu.getSelectedIndex();
            
            if (idx != -1) {
                  mode = "on";
                  judul.setText(us.getList_lagu().get(idx).getJudul());
                  int temp = us.getList_lagu().get(idx).getPutar();
                  muter.setText(String.valueOf(temp));
                  button();
            }
      }//GEN-LAST:event_listLaguMouseClicked

      private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
            this.dispose();
            FormUser f = new FormUser(us);
            f.setVisible(true);
      }//GEN-LAST:event_backActionPerformed

      private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
            int idx = listLagu.getSelectedIndex();
            us.hapus_lagu(idx);
            mode = "off";
            button();
            print();
      }//GEN-LAST:event_clearActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(FormBrowse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(FormBrowse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(FormBrowse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(FormBrowse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new FormBrowse().setVisible(true);
                  }
            });
      }
      
      public void print() {
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < us.getList_lagu().size(); i++) {
                  model.addElement(us.kalimat(i));
            }
            listLagu.setModel(model);
      }
      
      public void button() {
            if (mode.equals("off")) {
                  b_denger.setEnabled(false);
                  clear.setEnabled(false);
            } else if (mode.equals("on")) {
                  b_denger.setEnabled(true);
                  clear.setEnabled(true);
            }
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JLabel a;
      private javax.swing.JLabel b;
      private javax.swing.JButton b_denger;
      private javax.swing.JButton back;
      private javax.swing.JButton clear;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JLabel judul;
      private javax.swing.JList<String> listLagu;
      private javax.swing.JLabel muter;
      // End of variables declaration//GEN-END:variables
}
